version: 0.0
os: linux
files:
  - source: /
    destination: /data/story-sso/
    #destination: /home/ssm-user/story-sso/
permissions:
#  - object: /home/ssm-user/story-sso/
  - object: /data/story-sso/
    pattern: "**"
    owner : tomcat
    group: users
hooks:
  AfterInstall:
    - location: scripts/start.sh
      timeout: 300
      runas: ssm-user