# default는 운영으로
server:
  port: 8081

spring:
  mvc:
    view:
      prefix: "/WEB-INF/"
      suffix: ".jsp"
  config:
    activate:
      on-profile: default
logging:
  level:
    root: DEBUG

amore:
  story:
    url: "https://stories.amorepacific.com"


---
server:
  port: 8081

spring:
  mvc:
    view:
      prefix: "/WEB-INF/"
      suffix: ".jsp"
  config:
    activate:
      on-profile: stage
logging:
  level:
    root: DEBUG

amore:
  story:
    url: "https://dev.stories.amorepacific.com"


---
server:
  port: 8081

spring:
  mvc:
    view:
      prefix: "/WEB-INF/"
      suffix: ".jsp"
  config:
    activate:
      on-profile: product
logging:
  level:
    root: DEBUG

amore:
  story:
    url: "https://stories.amorepacific.com"
